"""Shared driver and launch parameter defaults."""

DEFAULT_PARAMETERS = {
    'transport': 'ws',
    'device_uri': 'ws://192.168.1.7/ws',
    'auto_connect': False,
    'auto_reconnect': False,
    'reconnect_interval': 2.0,
    'frame_id': 'axiom',
    'sensor_frames': '{}',
    'topic_aliases': '{}',
    'ws_pcol': 'RICSerial',
    'serial.port': '/dev/ttyUSB0',
    'serial.baud': 115200,
    'serial.timeout': 0.02,
    'serial.mode': 'auto',
    'autosub': False,
    'publish_rate_hz': 10.0,
    'publish_trigger': 'time',
    'rpc_default_timeout': 3.0,
    'sensor_qos.reliability': 'best_effort',
    'sensor_qos.depth': 10,
    'sensor_qos.overrides': '{}',
    'publish_custom_messages': True,
    'range.field_of_view': 0.0,
    'metadata_refresh_s': 30.0,
    'receive_queue_depth': 256,
    'stale_after_s': 5.0,
}
